"""Planned maintenance: plans, the tasks they generate, and the windows work happens in
(spec §7.5.1) — Phase 5 Lane 5A. ``MAINTENANCE_ENABLED`` defaults to **false**.

Three tables, all created by the generic additive migration (``db/migrate.py`` walks
``Base.metadata``; ``db/models_all.py`` already imports this module before it runs), so
there is no hand-written DDL here and no ``SCHEMA_VERSION`` to bump.

Why three tables and not one
----------------------------
They answer three different questions and they change at three different rates.

``maintenance_plans``
    *What must be done, how often, and under which standard.* A policy row. It is written
    once when Planning agrees an interval and then barely touched. ``standard_ref`` is NOT
    NULL on purpose: every interval in §7.5.1 is **secondary-sourced** (NFPA 110, IEEE
    1187/1188 and TIA-222 are all paywalled), so a plan that cannot name the practice it
    claims to follow has no business taking a site off air. The value is a citation for a
    human to check, never something this system verifies.

``maintenance_tasks``
    *One occurrence of a plan at one site, due at one moment.* Generated by the
    ``maintenance_plan_due`` job, gated by ``APPROVE_SCHEDULE``, and completed by a person.
    High churn, short life.

``maintenance_windows``
    *A period during which customers are deliberately off air.* This is the row with
    commercial and regulatory weight: it carries the iCalendar identity the invite is sent
    under (``uid``/``sequence``), the CA licence Condition 9.1 written-approval reference,
    the customer-notice timestamp, and the rain-season flag. It outlives the tasks inside
    it, because the evidence that a given outage was *planned* is what keeps it out of the
    vendor's SLA figure a quarter later.

Windows and tasks are therefore many-to-one and **not** a foreign key from the window side:
one window can host several tasks (a generator exercise and a battery check on the same
night), and a task can exist with no window at all while it is still PROPOSED.

Operator scoping (§8)
---------------------
``maintenance_plans`` and ``maintenance_windows`` carry their own ``operator_id``, exactly
as the spec's DDL does, so ``api.deps._owned`` filters them directly with no join.

``maintenance_tasks`` deliberately does **not** — see the comment on
:class:`MaintenanceTaskRow`. It is owned through ``plan_id -> maintenance_plans.operator_id``
and every read goes through ``services.maintenance.owned_tasks``, which puts that join in the
WHERE clause. Registering it with ``api.deps.register_owned_via_incident`` would be wrong:
that door is for tables owned through ``incident_id``, and a maintenance task has no
incident.

Status vocabularies are plain strings with no CHECK constraint, matching
``incidents.status`` and ``regulatory_notifications.status``: the vocabulary and every
transition between its members are enforced by ``services/maintenance.py``, which is the
only module allowed to write these tables.
"""

from __future__ import annotations

from datetime import datetime

from sqlalchemy import DateTime, Index, Integer, String, Text, text
from sqlalchemy.orm import Mapped, mapped_column

from noc_agents.db.models import Base, new_id, utcnow

__all__ = [
    "CONSUMPTION_DRIVEN_TASK_TYPES",
    "MAINTENANCE_TASK_TYPES",
    "TASK_STATUSES",
    "WINDOW_SCOPES",
    "WINDOW_STATUSES",
    "MaintenancePlanRow",
    "MaintenanceTaskRow",
    "MaintenanceWindowRow",
    "TASK_CANCELLED",
    "TASK_DONE",
    "TASK_IN_PROGRESS",
    "TASK_INVITED",
    "TASK_MISSED",
    "TASK_PROPOSED",
    "TASK_SCHEDULED",
    "WINDOW_CANCELLED",
    "WINDOW_COMPLETED",
    "WINDOW_PROPOSED",
    "WINDOW_SCHEDULED",
]

#: ``maintenance_plans.task_type`` (§7.5.1), in the spec's order. A closed set: each member
#: has its own interval and its own named standard, so a typo must fail at the service
#: boundary rather than quietly become an eleventh kind of work nobody has an interval for.
MAINTENANCE_TASK_TYPES: tuple[str, ...] = (
    "GENERATOR_EXERCISE",
    "GENERATOR_LOAD_BANK",
    "FUEL_RUN",
    "BATTERY_CHECK",
    "BATTERY_CAPACITY",
    "TOWER_VISUAL",
    "TOWER_STRUCTURAL",
    "FIBRE_PATROL",
    "AC_SERVICE",
    "GROUNDING_CHECK",
)

#: The task types the calendar cannot schedule on its own. §7.5.1 marks ``FUEL_RUN`` as
#: ``consumption_driven: true`` — it follows the genset's burn rate and the last fill, not a
#: fixed number of days. The due-date function refuses to invent a date for these rather than
#: guessing one (see ``services.maintenance.next_due``); a fuel run proposed on the wrong day
#: is either a wasted truck roll or a site that runs dry.
CONSUMPTION_DRIVEN_TASK_TYPES: frozenset[str] = frozenset({"FUEL_RUN"})

#: ``maintenance_tasks.status`` (§7.5.1).
TASK_PROPOSED = "PROPOSED"
TASK_SCHEDULED = "SCHEDULED"
TASK_INVITED = "INVITED"
TASK_IN_PROGRESS = "IN_PROGRESS"
TASK_DONE = "DONE"
TASK_MISSED = "MISSED"
TASK_CANCELLED = "CANCELLED"
TASK_STATUSES: tuple[str, ...] = (
    TASK_PROPOSED,
    TASK_SCHEDULED,
    TASK_INVITED,
    TASK_IN_PROGRESS,
    TASK_DONE,
    TASK_MISSED,
    TASK_CANCELLED,
)

#: ``maintenance_windows.status`` (§7.5.1). There is deliberately no ``APPROVED`` member, for
#: the same reason ``regulatory_notifications`` has none: approval is not a state of the
#: window, it is a fact about a named human recorded on ``hitl_tasks`` and mirrored here as
#: ``approved_by``. ``SCHEDULED`` is the *consequence* of an approval that
#: ``services.maintenance.window_approval_of`` verified against the database, and it is the
#: only status in which a window may take customers off air.
WINDOW_PROPOSED = "PROPOSED"
WINDOW_SCHEDULED = "SCHEDULED"
WINDOW_CANCELLED = "CANCELLED"
WINDOW_COMPLETED = "COMPLETED"
WINDOW_STATUSES: tuple[str, ...] = (WINDOW_PROPOSED, WINDOW_SCHEDULED, WINDOW_CANCELLED, WINDOW_COMPLETED)

#: ``maintenance_windows.scope`` (§7.5.1). REGION and NETWORK additionally require a CA
#: Condition 9.1 written-approval reference before they may be SCHEDULED (§7.5.6, decision D8
#: leaves SITE out); that rule lives in ``services/maintenance.py``.
WINDOW_SCOPES: tuple[str, ...] = ("SITE", "REGION", "NETWORK")


class MaintenancePlanRow(Base):
    """One preventive-maintenance policy: this work, at this scope, this often (§7.5.1).

    ``site_id`` **or** ``site_class`` — exactly one, which the service enforces
    (:func:`services.maintenance.validate_plan`) rather than a CHECK constraint, so the 422
    can say which one is missing. A plan scoped by class ("every CRITICAL site") is what makes
    the lane usable across 6 000 sites; a plan scoped by id is what a single diesel generator
    with a bad history needs.

    ``interval_days`` / ``interval_hours`` are both nullable and both may be NULL at once —
    that is the ``consumption_driven`` case (``FUEL_RUN``), where the calendar is not the
    driver at all.
    """

    __tablename__ = "maintenance_plans"
    __table_args__ = (
        Index("ix_maint_plans_operator_active", "operator_id", "active"),
        Index("ix_maint_plans_operator_site", "operator_id", "site_id"),
    )

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    operator_id: Mapped[str] = mapped_column(String(32), index=True)
    # Exactly one of these two is set; see the class docstring.
    site_id: Mapped[str | None] = mapped_column(String(64), nullable=True)
    site_class: Mapped[str | None] = mapped_column(String(32), nullable=True)
    task_type: Mapped[str] = mapped_column(String(32), index=True)  # MAINTENANCE_TASK_TYPES
    interval_days: Mapped[int | None] = mapped_column(Integer, nullable=True)
    interval_hours: Mapped[int | None] = mapped_column(Integer, nullable=True)
    consumption_driven: Mapped[int] = mapped_column(Integer, default=0, server_default=text("0"))
    # The vendor who owns the work, when one does (an FK in spirit to ``vendors.id``, but not
    # declared as one: the vendors table belongs to another lane and a hard FK here would make
    # this module fail to import if that lane were ever removed).
    owner_vendor_id: Mapped[str | None] = mapped_column(String(36), nullable=True)
    # NOT NULL, and the reason is in the module docstring: every shipped interval is
    # secondary-sourced, so the citation travels with the policy.
    standard_ref: Mapped[str] = mapped_column(Text)
    active: Mapped[int] = mapped_column(Integer, default=1, server_default=text("1"))
    created_at: Mapped[datetime] = mapped_column(DateTime, default=utcnow)


class MaintenanceTaskRow(Base):
    """One occurrence of a plan, at one site, due at one moment (§7.5.1).

    **Operator scoping.** No ``operator_id`` column, on purpose: the spec's DDL has none and
    the value is derivable from ``plan_id -> maintenance_plans.operator_id``. A denormalised
    copy here would be a second version of a derivable fact that can drift from the first —
    the same argument ``api/deps.py`` makes for ``hitl_tasks`` and ``db/models_pir.py`` makes
    for ``pir_action_items``. Every read goes through
    ``services.maintenance.owned_tasks(session, operator_id)``, which joins the plan and puts
    the operator clause in the WHERE, so the rows a caller can see are bounded by the query
    and never by a check after the fetch.

    ``proposed_assignee_token`` and ``assignee_token`` are **role tokens** (``FE-NBI-E-01``,
    ``MSP_POWER``, ``EGYPRO``), never a person's name — §7.11.8 and §7.7.6. The proposal is
    what the job worked out from the region roster; the second column is what a human
    actually approved, and keeping them apart is what makes "the system proposed X and a human
    changed it to Y" visible on the card instead of being overwritten in place.

    ``completed_by`` is the one field here that legitimately holds a human name: it is the
    signature on a piece of physical work, the same category as ``incidents.restored_by``.
    """

    __tablename__ = "maintenance_tasks"
    __table_args__ = (
        Index("ix_maint_tasks_plan_site_due", "plan_id", "site_id", "due_at"),
        Index("ix_maint_tasks_status_due", "status", "due_at"),
        Index("ix_maint_tasks_window", "window_id"),
    )

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    plan_id: Mapped[str] = mapped_column(String(36), index=True)
    site_id: Mapped[str] = mapped_column(String(64), index=True)
    due_at: Mapped[datetime] = mapped_column(DateTime)  # naive UTC, the storage contract (§7.0.6)
    window_id: Mapped[str | None] = mapped_column(String(36), nullable=True)
    proposed_assignee_token: Mapped[str | None] = mapped_column(String(64), nullable=True)
    assignee_token: Mapped[str | None] = mapped_column(String(64), nullable=True)
    # The APPROVE_SCHEDULE card. Mirrored here for readers; the AUTHORITY is the row in
    # hitl_tasks that ``services.maintenance.schedule_approval_of`` re-reads and re-checks.
    hitl_task_id: Mapped[str | None] = mapped_column(String(36), nullable=True)
    status: Mapped[str] = mapped_column(String(16), default=TASK_PROPOSED, server_default=TASK_PROPOSED)
    completed_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
    completed_by: Mapped[str | None] = mapped_column(Text, nullable=True)
    evidence_note: Mapped[str | None] = mapped_column(Text, nullable=True)
    # What was found, in the engineer's words: "ran 45 min at 40 % load, coolant topped up".
    # Free text, because a fixed vocabulary here is how "generator would not start" becomes
    # "OTHER" and stops being searchable.
    outcome: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime, default=utcnow)


class MaintenanceWindowRow(Base):
    """A period during which customers are deliberately off air (§7.5.1).

    ``starts_at`` / ``ends_at`` are naive **UTC**, like every other instant in this schema
    (§7.0.6). The floor and the customer notice both read EAT, and that conversion happens
    once, on the way out, through ``services.clock.fmt_eat``. The bug this avoids is storing
    a value that was already converted to EAT: a 00:00–05:00 EAT window written as if it were
    UTC starts at 03:00 EAT, three hours into the morning peak.

    ``uid`` and ``sequence`` are the RFC 5545 calendar identity. ``uid`` is allocated once, at
    creation, and never changes for the life of the window — it is what lets a later
    ``METHOD:REQUEST`` update, or a ``METHOD:CANCEL``, land on the invite already in the
    engineer's calendar rather than creating a second entry. ``sequence`` is bumped by
    ``services.maintenance.bump_sequence`` on every reschedule or cancellation, because a
    client that receives a REQUEST whose SEQUENCE has not advanced is entitled to ignore it.

    ``attendees_ref`` is a **config path** (``audiences.FE_ONCALL``), never an address list:
    recipients are resolved at dispatch, exactly like every other audience in this system, so
    a personal e-mail address is never stored on an operational row (§7.5.6 — attendee
    addresses are personal data).

    ``rain_season_flag`` is written by the rain guard and is a *warning for the approver*, not
    a lock. What it must never be is a silent zero: see
    ``services.maintenance.rain_guard`` — "no forecast" is recorded as its own verdict and is
    never rendered as "no rain".
    """

    __tablename__ = "maintenance_windows"
    __table_args__ = (
        Index("ix_maint_windows_operator_status_start", "operator_id", "status", "starts_at"),
        Index("ix_maint_windows_scope", "operator_id", "scope", "scope_ref"),
    )

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    operator_id: Mapped[str] = mapped_column(String(32), index=True)
    scope: Mapped[str] = mapped_column(String(16))  # WINDOW_SCOPES
    # A site id for SITE, a region code for REGION, the operator id (or "ALL") for NETWORK.
    scope_ref: Mapped[str] = mapped_column(String(64))
    starts_at: Mapped[datetime] = mapped_column(DateTime, index=True)
    ends_at: Mapped[datetime] = mapped_column(DateTime)
    uid: Mapped[str] = mapped_column(String(128), unique=True)
    sequence: Mapped[int] = mapped_column(Integer, default=0, server_default=text("0"))
    rrule: Mapped[str | None] = mapped_column(Text, nullable=True)  # RFC 5545 RRULE for a recurring window
    organizer: Mapped[str] = mapped_column(Text)
    attendees_ref: Mapped[str] = mapped_column(Text)  # a config path, never addresses
    status: Mapped[str] = mapped_column(String(16), default=WINDOW_PROPOSED, server_default=WINDOW_PROPOSED)
    # CA licence Condition 9.1: prior WRITTEN Authority approval before any intentional
    # interruption in the normal course of business. Mandatory before a REGION/NETWORK window
    # may be SCHEDULED (§7.5.6). UNVERIFIED for this operator's actual licence — confirm with
    # Legal before the lane is enabled.
    ca_approval_ref: Mapped[str | None] = mapped_column(Text, nullable=True)
    customer_notice_sent_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
    approved_by: Mapped[str | None] = mapped_column(Text, nullable=True)
    # The APPROVE_MAINTENANCE_WINDOW card. Again a mirror: the authority is the hitl_tasks row.
    hitl_task_id: Mapped[str | None] = mapped_column(String(36), nullable=True)
    # Set when the window exists BECAUSE of an incident (emergency work arising from a PRB).
    # Also the preferred anchor for this window's HITL card — see services.maintenance.anchor_incident.
    incident_id: Mapped[str | None] = mapped_column(String(36), nullable=True, index=True)
    rain_season_flag: Mapped[int] = mapped_column(Integer, default=0, server_default=text("0"))
    created_at: Mapped[datetime] = mapped_column(DateTime, default=utcnow)
