"""Live demo scenarios — heavy rains / MW cascade across Safaricom regions."""

from __future__ import annotations

from noc_agents.domain.schemas import EventIngest

# Heavy rains: Rift + Mt Kenya + Nairobi East — MW links drop → parent HUBs
# then child sites cascade (same parent_hub_id).
RAIN_STORM_EVENTS: list[EventIngest] = [
    EventIngest(
        site_id="SFC-RFT-HUB-NKR",
        site_name="Nakuru Rift HUB",
        site_type="HUB",
        region_code="RFT",
        county="Nakuru",
        alarm_code="MW_HOP_DOWN",
        failure_domain="TRANSMISSION",
        users_affected=280000,
        child_sites_down=12,
        description="Heavy rains — primary MW hop to Nakuru aggregation down; cascade risk",
        access_notes="Roads slippery; FE ETA delayed",
        technology=["MW", "4G"],
    ),
    EventIngest(
        site_id="SFC-RFT-ENB-NKR-A1",
        site_name="Nakuru Sector A1 eNodeB",
        site_type="ENODEB",
        region_code="RFT",
        alarm_code="SITE_DOWN",
        failure_domain="TRANSMISSION",
        users_affected=18000,
        parent_hub_id="SFC-RFT-HUB-NKR",
        description="Child site offline — backhaul via failed MW hop",
        technology=["4G"],
    ),
    EventIngest(
        site_id="SFC-RFT-ENB-NKR-B3",
        site_name="Nakuru Sector B3 eNodeB",
        site_type="ENODEB",
        region_code="RFT",
        alarm_code="SITE_DOWN",
        failure_domain="TRANSMISSION",
        users_affected=15000,
        parent_hub_id="SFC-RFT-HUB-NKR",
        description="Child site offline — MW cascade",
        technology=["4G"],
    ),
    EventIngest(
        site_id="SFC-RFT-HUB-ELD",
        site_name="Eldoret Rift HUB",
        site_type="HUB",
        region_code="RFT",
        county="Uasin Gishu",
        alarm_code="POWER_GRID_FAIL",
        failure_domain="POWER",
        users_affected=210000,
        description="Storm grid trip — genset start delay at Eldoret HUB",
        battery_countdown_min=40,
        technology=["4G", "2G"],
    ),
    EventIngest(
        site_id="SFC-MTK-HUB-THK",
        site_name="Thika Mt Kenya HUB",
        site_type="HUB",
        region_code="MTK",
        county="Kiambu",
        alarm_code="MW_HIGH_BER",
        failure_domain="TRANSMISSION",
        users_affected=195000,
        child_sites_down=8,
        description="Heavy rains Mt Kenya — MW high BER / fade on highland hop",
        technology=["MW", "4G"],
    ),
    EventIngest(
        site_id="SFC-MTK-ENB-MRI-01",
        site_name="Meru Spur eNodeB 01",
        site_type="ENODEB",
        region_code="MTK",
        alarm_code="SITE_DOWN",
        failure_domain="TRANSMISSION",
        users_affected=9000,
        parent_hub_id="SFC-MTK-HUB-THK",
        description="Spur site down after Thika MW degradation",
        technology=["4G"],
    ),
    EventIngest(
        site_id="SFC-MTK-BTS-MRI08",
        site_name="Meru Rural BTS 08",
        site_type="BTS",
        region_code="MTK",
        alarm_code="SITE_DOWN",
        failure_domain="TRANSMISSION",
        users_affected=3200,
        parent_hub_id="SFC-MTK-HUB-THK",
        description="Rural BTS lost MW backhaul",
        technology=["2G", "3G"],
    ),
    EventIngest(
        site_id="SFC-NBIE-HUB-EMB",
        site_name="Embakasi East Aggregation HUB",
        site_type="HUB",
        region_code="NBI_E",
        county="Nairobi",
        alarm_code="MW_HOP_DOWN",
        failure_domain="TRANSMISSION",
        users_affected=420000,
        child_sites_down=15,
        description="Nairobi East — metro MW link fail under storm cells; multi-site risk",
        technology=["MW", "4G", "5G"],
    ),
    EventIngest(
        site_id="SFC-NBIE-ENB-KAY12",
        site_name="Kayole eNodeB 12",
        site_type="ENODEB",
        region_code="NBI_E",
        alarm_code="SITE_DOWN",
        failure_domain="TRANSMISSION",
        users_affected=24000,
        parent_hub_id="SFC-NBIE-HUB-EMB",
        description="Eastlands site down — parent HUB MW cascade",
        technology=["4G"],
    ),
    EventIngest(
        site_id="SFC-NBIE-ENB-UMB04",
        site_name="Umoja eNodeB 04",
        site_type="ENODEB",
        region_code="NBI_E",
        alarm_code="SITE_DOWN",
        failure_domain="TRANSMISSION",
        users_affected=19000,
        parent_hub_id="SFC-NBIE-HUB-EMB",
        description="Umoja offline — MW cascade from Embakasi HUB",
        technology=["4G"],
    ),
    EventIngest(
        site_id="SFC-NBIE-TX-MW-EAST1",
        site_name="Nairobi East MW Ring Node",
        site_type="TX",
        region_code="NBI_E",
        alarm_code="MW_HOP_DOWN",
        failure_domain="TRANSMISSION",
        users_affected=80000,
        description="MW ring node — rain fade / path obstruction",
        technology=["MW"],
    ),
]


def scenario_payload() -> list[dict]:
    return [e.model_dump(mode="json") for e in RAIN_STORM_EVENTS]
